// Package bindgen generates Go source code from a fully-resolved WIT package.
// It generates one or more Go packages, with functions, types, constants, and variables,
// along with the associated code to lift and lower Go types into Canonical ABI representation.
package bindgen

const HeaderPattern = `// Code generated by %s. DO NOT EDIT.`

type Config struct {
	// Remap maps WIT identifiers to Go identifiers. Examples:
	// "wasi:clocks" -> "wasi/clocks"
	// "wasi:clocks/wall-clock" -> "wasi/clocks/wall"
	// "wasi:clocks/wall-clock" -> "wasi/clocks/wall#wallclock" (for a Go short package name of wallclock)
	// "wasi:clocks/wall-clock.datetime" -> "wasi/clocks/wall#DateTime"
	// "wasi:clocks/wall-clock.now" -> "wasi/clocks/wall#Now"
	Remap map[string]string
}
