// Package bindgen generates Go source code from a fully-resolved WIT package.
// It generates one or more Go packages, with functions, types, constants, and variables,
// along with the associated code to lift and lower Go types into Canonical ABI representation.
package bindgen

import (
	"fmt"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/ydnar/wasm-tools-go/internal/codec"
	"github.com/ydnar/wasm-tools-go/internal/go/gen"
	"github.com/ydnar/wasm-tools-go/wit"
)

const HeaderPattern = `// Code generated by %s. DO NOT EDIT.`

// Go generates one or more Go packages from [wit.Resolve] res.
// It returns any error that occurs during code generation.
func Go(res *wit.Resolve, opts ...Option) ([]*gen.Package, error) {
	g, err := newGenerator(res, opts...)
	if err != nil {
		return nil, err
	}

	fmt.Printf(HeaderPattern, g.opts.generator)
	fmt.Println()
	err = g.generateWorlds()
	if err != nil {
		return nil, err
	}

	return g.finish()
}

type generator struct {
	opts              options
	res               *wit.Resolve
	packages          map[string]*gen.Package
	worldPackages     map[*wit.World]*gen.Package
	interfacePackages map[*wit.Interface]*gen.Package
	packageMap        map[string]*gen.Package
}

func newGenerator(res *wit.Resolve, opts ...Option) (*generator, error) {
	g := &generator{}
	err := g.opts.apply(opts...)
	if err != nil {
		return nil, err
	}
	if g.opts.generator == "" {
		_, file, _, _ := runtime.Caller(0)
		_, g.opts.generator = filepath.Split(filepath.Dir(filepath.Dir(file)))
	}
	g.res = res
	return g, nil
}

func (g *generator) finish() ([]*gen.Package, error) {
	var packages []*gen.Package
	for _, path := range codec.SortedKeys(g.packages) {
		packages = append(packages, g.packages[path])
	}
	return packages, nil
}

// By default, each WIT interface and world maps to a single Go package.
// Options might override the Go package, including combining multiple
// WIT interfaces and/or worlds into a single Go package.
func (g *generator) generateWorlds() error {
	fmt.Printf("Generating Go for %d world(s)\n\n", len(g.res.Worlds))
	for _, w := range g.res.Worlds {
		g.generateWorld(w)
	}
	return nil
}

func (g *generator) generateWorld(w *wit.World) error {
	fmt.Println(w.Path())
	for _, name := range codec.SortedKeys(w.Imports) {
		var err error
		switch v := w.Imports[name].(type) {
		case *wit.Interface:
			err = g.generateImportedInterface(w, v, name)
		case *wit.TypeDef:
			err = g.generateImportedTypeDef(w, v, name)
		case *wit.Function:
			err = g.generateImportedFunction(w, v)
		}
		if err != nil {
			return err
		}
	}
	fmt.Println()
	return nil
}

func (g *generator) generateImportedInterface(w *wit.World, i *wit.Interface, name string) error {
	if i.Name != nil {
		name = *i.Name
	}
	fmt.Printf("\timport interface %s/%s\n", w.Path(), name)
	return nil
}

func (g *generator) generateImportedTypeDef(w *wit.World, t *wit.TypeDef, name string) error {
	if t.Name != nil {
		name = *t.Name
	}
	fmt.Printf("\timport type %s.%s\n", w.Path(), name)
	return nil
}

func (g *generator) generateImportedFunction(w *wit.World, f *wit.Function) error {
	fmt.Printf("\timport func %s.%s\n", w.Path(), f.Name)
	return nil
}

// packageForWorld returns a Go package for [wit.World] w.
// It attempts to map the WIT package and world name to a Go package path,
// using the mappings in g.opts if present.
func (g *generator) packageForWorld(w *wit.World) *gen.Package {
	// Find existing.
	if p, ok := g.worldPackages[w]; ok {
		return p
	}

	// Create a new package.
	var path string
	var name string
	if mapped, ok := g.opts.idents[w.Package.Name.ShortString()+"/"+w.Name]; ok {
		path, name = gen.ParseSelector(mapped)
	} else if mapped, ok := g.opts.idents[w.Package.Name.ShortString()]; ok {
		path, name = gen.ParseSelector(mapped + "/" + w.Name)
	} else {
		path = w.Package.Name.Namespace + "/" + w.Package.Name.Name + "/" + w.Name
		name = w.Name
	}
	var _, _ = path, name
	return nil
}

func (g *generator) packageName(s string) (path, name string) {
	if pkg, ok := g.packageMap[s]; ok {
		return pkg.Path, pkg.Name
	}

	// Try to map full string to Go package string, e.g. "wasi:clocks/monotonic-clock"
	if mapped, ok := g.opts.idents[s]; ok {
		return gen.ParseSelector(mapped)
	}

	// Extract package name from s, e.g. "wasi:clocks"
	if pkg, dir, ok := strings.Cut(s, "/"); ok {
		if mapped, ok := g.opts.idents[pkg]; ok {
			return gen.ParseSelector(mapped + "/" + dir)
		}
	}

	return "", ""
}

func worldIdent(w *wit.World) wit.Ident {
	var id wit.Ident
	id.Package = w.Package.Name.ShortString()
	id.Interface = w.Name
	return id
}
