// Package bindgen generates Go source code from a fully-resolved WIT package.
// It generates one or more Go packages, with functions, types, constants, and variables,
// along with the associated code to lift and lower Go types into Canonical ABI representation.
package bindgen

import (
	"fmt"
	"strings"

	"github.com/ydnar/wasm-tools-go/internal/codec"
	"github.com/ydnar/wasm-tools-go/internal/go/gen"
	"github.com/ydnar/wasm-tools-go/wit"
)

const HeaderPattern = `// Code generated by %s. DO NOT EDIT.`

// Go generates one or more Go packages from [wit.Resolve] res.
// It returns any error that occurs during code generation.
func Go(res *wit.Resolve, opts ...Option) ([]*gen.Package, error) {
	g, err := newGenerator(res, opts...)
	if err != nil {
		return nil, err
	}

	// By default, each WIT interface and world maps to a single Go package.
	// Options might override the Go package, including combining multiple
	// WIT interfaces and/or worlds into a single Go package.
	for _, w := range g.res.Worlds {
		id := worldIdent(w)
		fmt.Printf("%s → %s\n", id, id)
	}

	return g.finish()
}

type generator struct {
	opts       options
	res        *wit.Resolve
	packages   map[string]*gen.Package
	packageMap map[wit.Ident]*gen.Package
}

func newGenerator(res *wit.Resolve, opts ...Option) (*generator, error) {
	state := &generator{}
	err := state.opts.apply(opts...)
	if err != nil {
		return nil, err
	}
	state.res = res
	return state, nil
}

func (g *generator) finish() ([]*gen.Package, error) {
	var packages []*gen.Package
	for _, path := range codec.SortedKeys(g.packages) {
		packages = append(packages, g.packages[path])
	}
	return packages, nil
}

func (g *generator) goPackageIdent(id wit.Ident) gen.Ident {
	// Remove Name field, which doesn’t affect package path.
	id = id.InterfaceIdent()

	// Check existing Go packages first.
	if pkg, ok := g.packageMap[id]; ok {
		return pkg.Ident
	}

	// Check ident mappings.
	if gid, ok := g.opts.idents[id]; ok {
		return gid
	}
	var base string
	if gid, ok := g.opts.idents[id.PackageIdent()]; ok {
		base = gid.Path
	} else {
		base = strings.ReplaceAll(id.Package, ":", "/")
	}

	// Concatenate
	if id.Interface != "" {
		return gen.Ident{
			// TODO: strip '-' characters
			Path: base + "/" + id.Interface,
		}
	}

	return gen.Ident{Path: base}
}

func worldIdent(w *wit.World) wit.Ident {
	var id wit.Ident
	id.Package = w.Package.Name.ShortString()
	id.Interface = w.Name
	return id
}
