package bindgen

// Option represents a single configuration option for this package.
type Option interface {
	applyOption(*options)
}

type optionFunc func(*options)

func (f optionFunc) applyOption(opts *options) {
	f(opts)
}

type options struct {
	// generator is the name of the program that generates code with this package.
	generator string

	// idents maps WIT identifiers to Go identifiers. Examples:
	// "wasi:clocks" -> "wasi/clocks"
	// "wasi:clocks/wall-clock" -> "wasi/clocks/wall"
	// "wasi:clocks/wall-clock" -> "wasi/clocks/wall#wallclock" (for a Go short package name of wallclock)
	// "wasi:clocks/wall-clock.datetime" -> "wasi/clocks/wall#DateTime"
	// "wasi:clocks/wall-clock.now" -> "wasi/clocks/wall#Now"
	idents map[string]string
}

func (opts *options) apply(o ...Option) {
	for _, o := range o {
		o.applyOption(opts)
	}
}

// GeneratedBy returns an [Option] that specifies the name of the program or package
// that will appear in the "Code generated by ..." header on generated files.
func GeneratedBy(name string) Option {
	return optionFunc(func(opts *options) {
		opts.generator = name
	})
}

// MapIdent returns an [Option] that maps a [WIT] identifier to a Go identifier.
//
// Acceptable values for from include: package names like "wasi:clocks",
// qualified interface or world names like "wasi:clocks/wall-clock",
// or fully-qualified identifiers like "wasi:clocks/wall-clock.datetime".
//
// Acceptable values for to include: Go package paths like "wasi/clocks/wallclock",
// qualified package names like "wasi/clocks/wall#wallclock", or
// qualified identifier names like "wasi/clocks/wallclock#DateTime".
//
// [WIT]: https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md
func MapIdent(from, to string) Option {
	return optionFunc(func(opts *options) {
		if opts.idents == nil {
			opts.idents = make(map[string]string)
		}
		opts.idents[from] = to
	})
}

// MapIdents returns an [Option] that maps [WIT] identifiers to Go identifiers.
// See [MapIdent] for more information.
//
// [WIT]: https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md
func MapIdents(idents map[string]string) Option {
	return optionFunc(func(opts *options) {
		if opts.idents == nil {
			opts.idents = make(map[string]string, len(idents))
		}
		for from, to := range idents {
			opts.idents[from] = to
		}
	})
}
